### ISSUE TITLE
TCP mode questions..

### ISSUE THREAD

**Issue by r4ravi2008** [hartfordfive/protologbeat#15]
I have been trying to forward the events using TCP mode, and the plugin seems to forward only the first TCP event it receives after establishing a TCP connection. How can I debug this? The debug mode doesn't seem to be of much help.

I tested this using `ncat`. And the plugin seems to send `RST` packet after receiving first packet.

Here is the config I am using:

```
protologbeat:
  address: "127.0.0.1"
  port: 25001
  max_msg_size: 65535
  protocol: tcp
output.logstash:
  # The Logstash hosts
  hosts: ["172.16.1.64:5044"]
```
